version: "3"

services:
  db:
    image: postgres:latest
    container_name: lamb-db
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data
    networks:
      - app-db-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: on-failure

  pgmyadmin:
    image: dpage/pgadmin4:latest
    container_name: lamb-pgmyadmin
    ports:
      - 80:80
    networks:
      - app-db-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_USER: ${DB_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    restart: on-failure

  app:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: production
    container_name: lamb-app
    ports:
      - 8000:8000
    networks:
      - app-db-network
    depends_on:
      - db
    restart: on-failure

volumes:
  app-db-data:
    driver: local

networks:
  app-db-network:
    driver: bridge
